/*
 4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
‌
 */
package Day_2.part_3;

import java.util.Scanner;
import java.util.Arrays;

public class Random_Shuffling_String {
    static Scanner scan = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.print("Enter the String 1 :");
        String str = scan.nextLine();
        System.out.print("Enter the String 1 :");
        String str1 = scan.nextLine();
        System.out.println("Random Shuffling String : " + random_Shuffling_String(str, str1));
    }
    // Shuffling The String Check
    public static char random_Shuffling_String(String str, String str1) {
        int[] letter = new int[26];
        for (int j = 0; j < str1.length(); j++) {
            letter[str1.charAt(j) - 'a']++;
        }
        for (int i = 0; i < str.length(); i++)
            letter[str.charAt(i) - 'a']--;
        for (int i = 0; i < letter.length; i++) {
            if (letter[i] != 0)
                return (char) (i + 'a');
        }
        return '\u0000';
    }
}
